# Generated by Django 5.1.4 on 2024-12-31 14:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='cv/')),
                ('lettre_motivation', models.FileField(upload_to='lettres/')),
                ('statut_candidature', models.CharField(choices=[('reçue', 'Reçue'), ('en_cours', 'En cours de traitement'), ('rejete', 'Rejetée'), ('acceptee', 'Acceptée')], default='reçue', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('competences', models.TextField(blank=True, verbose_name='Compétences')),
                ('historique_professionnel', models.TextField(blank=True, verbose_name='Historique professionnel')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Titre non spécifié', max_length=255)),
                ('description', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('lieu', models.CharField(default='Non précisé', max_length=255)),
                ('date_limite', models.DateTimeField(default=datetime.datetime(2025, 1, 30, 15, 11, 52, 330773))),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('periode_essai', models.BooleanField(default=False)),
                ('renouvellement', models.BooleanField(default=False)),
                ('salaire_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_quotidien', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('type_contrat', models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('Stage', 'Stage'), ('Autre', 'Autre')], max_length=50)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('Annuel', 'Congé Annuel'), ('Maladie', 'Congé Maladie'), ('Maternité', 'Congé Maternité/Paternité'), ('Sans Solde', 'Congé Sans Solde')], max_length=20, verbose_name='Type de congé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('jours_utilises', models.PositiveIntegerField(editable=False, verbose_name='Jours utilisés')),
                ('solde_initial', models.PositiveIntegerField(verbose_name='Solde initial')),
                ('solde_restant', models.PositiveIntegerField(editable=False, verbose_name='Solde restant')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='app1.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('raison', models.CharField(blank=True, max_length=200, null=True)),
                ('impact_salaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluation', models.DateField()),
                ('score', models.IntegerField()),
                ('commentaires', models.TextField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe')),
            ],
            options={
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('employes', models.ManyToManyField(related_name='formations', to='app1.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entretien', models.DateTimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.candidat')),
                ('offre_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.offreemploi')),
            ],
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prime', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_prime', models.CharField(choices=[('fixe', 'Fixe'), ('pourcentage', 'Pourcentage')], max_length=50)),
                ('base_calcul', models.DecimalField(decimal_places=2, default=30000, max_digits=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.service', verbose_name='Service'),
        ),
    ]
