# Generated by Django 5.1.4 on 2024-12-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_type_conge_contrat_type_contrat_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recrutement',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='conge',
            name='jours_utilises',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conge',
            name='solde_restant',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddConstraint(
            model_name='recrutement',
            constraint=models.UniqueConstraint(fields=('offre', 'employe'), name='unique_recrutement'),
        ),
    ]
