# Generated by Django 5.1.4 on 2024-12-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_recrutement_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='nom_service',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
