# Generated by Django 5.1.4 on 2024-12-26 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_service_nom_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='statut_candidature',
        ),
        migrations.AlterField(
            model_name='employe',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.service'),
        ),
    ]
