# Generated by Django 5.1.4 on 2024-12-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_candidature_statut_candidature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('raison', models.CharField(blank=True, max_length=200, null=True)),
                ('impact_salaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prime', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_prime', models.CharField(choices=[('fixe', 'Fixe'), ('pourcentage', 'Pourcentage')], max_length=50)),
                ('base_calcul', models.DecimalField(decimal_places=2, default=30000, max_digits=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe')),
            ],
        ),
    ]
