# Generated by Django 5.1.4 on 2024-12-28 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_absence_prime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conge',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Congé', 'verbose_name_plural': 'Congés'},
        ),
        migrations.AlterModelOptions(
            name='employe',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AddField(
            model_name='contrat',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrat',
            name='periode_essai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrat',
            name='renouvellement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conge',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='date_fin',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='app1.employe', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='jours_utilises',
            field=models.PositiveIntegerField(editable=False, verbose_name='Jours utilisés'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='solde_initial',
            field=models.PositiveIntegerField(verbose_name='Solde initial'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='solde_restant',
            field=models.PositiveIntegerField(editable=False, verbose_name='Solde restant'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='type_conge',
            field=models.CharField(choices=[('Annuel', 'Congé Annuel'), ('Maladie', 'Congé Maladie'), ('Maternité', 'Congé Maternité/Paternité'), ('Sans Solde', 'Congé Sans Solde')], max_length=20, verbose_name='Type de congé'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('Stage', 'Stage'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employe',
            name='adresse',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='competences',
            field=models.TextField(blank=True, verbose_name='Compétences'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_naissance',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='historique_professionnel',
            field=models.TextField(blank=True, verbose_name='Historique professionnel'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.service', verbose_name='Service'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('received', 'Reçue'), ('processing', 'En cours de traitement'), ('rejected', 'Rejetée'), ('accepted', 'Acceptée')], default='received', max_length=50)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.offreemploi')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.candidate')),
            ],
        ),
    ]
