# Generated by Django 5.1.4 on 2024-12-31 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_candidat_offre_emploi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='offre_emploi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.offreemploi'),
        ),
    ]
