# Generated by Django 5.1.4 on 2024-12-31 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_evaluation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masrouf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date_demande', models.DateField(verbose_name='Date de demande')),
            ],
            options={
                'verbose_name': 'Masrouf',
                'verbose_name_plural': 'Masroufs',
            },
        ),
        migrations.AlterModelOptions(
            name='salaire',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Salaire', 'verbose_name_plural': 'Salaires'},
        ),
        migrations.AlterField(
            model_name='salaire',
            name='date_paiement',
            field=models.DateField(verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='montant',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AddConstraint(
            model_name='salaire',
            constraint=models.UniqueConstraint(fields=('employe', 'date_paiement'), name='unique_salaire_par_mois'),
        ),
        migrations.AddField(
            model_name='masrouf',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe', verbose_name='Employé'),
        ),
        migrations.AddConstraint(
            model_name='masrouf',
            constraint=models.CheckConstraint(condition=models.Q(('montant__lte', 30000)), name='masrouf_montant_max'),
        ),
    ]
