# Generated by Django 5.1.4 on 2025-01-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_candidat_offre_emploi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entretien',
            name='offre_emploi',
        ),
    ]
