# Generated by Django 5.1.4 on 2025-01-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_entretien_offre_emploi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('status', models.CharField(choices=[('received', 'Reçue'), ('under_review', 'En cours de traitement'), ('rejected', 'Rejetée'), ('accepted', 'Acceptée')], default='received', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='offre_emploi',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='candidat',
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('interviewer', models.CharField(max_length=200)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='app1.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app1.joboffer'),
        ),
        migrations.DeleteModel(
            name='OffreEmploi',
        ),
        migrations.DeleteModel(
            name='Candidat',
        ),
        migrations.DeleteModel(
            name='Entretien',
        ),
    ]
