# Generated by Django 5.1.4 on 2025-01-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_application_joboffer_remove_candidat_offre_emploi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=1, verbose_name='Sexe'),
        ),
    ]
