# Generated by Django 5.1.4 on 2024-12-31 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_offreemploi_date_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='offre_emploi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.offreemploi'),
            preserve_default=False,
        ),
    ]
